### ISSUE TITLE
按需启动部分人物后出错

### ISSUE THREAD

**Issue by sweljulby** [NaturalWhiteX/vambox-release#12]
按需启动部分人物，进入游戏要求重新允许之前打开过的插件加载，包括jayjaywon的那些，然后打开场景，人物变形和贴图加载失败，变成默认的样子，红色错误提示大概是：at MVR.FileManagement.FileManager.RegisterPackage (System.String vpath) [0x00000] in <filename unknown>:
at MVR.FileManagement.FileManager.Refresh ( [0x00000] in <filename unknown>:0

**Comment by wojvshiwo** [comment]
老哥你是怎么解决的 @sweljulby
