### ISSUE TITLE
有些依赖，预设里不会识别上

### ISSUE THREAD

**Issue by qq347776574** [NaturalWhiteX/vambox-release#17]

**Comment by qq347776574** [comment]
![a782dcd36e4d8731b2cdd0547e24c2d1](https://github.com/user-attachments/assets/f30f81c8-7736-4e8b-9e14-6c76e6fa7e8d)

**Comment by qq347776574** [comment]
![677f03209f049c02c7c9d4fa22090a2c](https://github.com/user-attachments/assets/93af1df8-7ec3-49ba-895a-23270e03085c)

**Comment by NaturalWhiteX** [comment]
预设文件能发我看一下吗
