### ISSUE TITLE
添加方案附加包时，会出现勾选内容无法添加的情况

### ISSUE THREAD

**Issue by zx20085121996** [NaturalWhiteX/vambox-release#2]
添加前312包，勾选时可以看到已经增加为364包，保存后该方案依旧是312包
然后删除重新添加方案又出现另外一种bug
添加前500包，勾选时可以看到已经增加为513包，保存后该方案只有512包

**Comment by NaturalWhiteX** [comment]
这不是BUG，这是去重后的结果，例如现在有两个包：
1. D:\Games\VAM\AddonPakcages\AcidBubbles.Glance.23.var
2. D:\Games\VAM\AddonPakcages\Plugins\AcidBubbles.Glance.23.var
你选的时候，会提示你选中了两个包，但是放到方案里，我只能告诉你，你只选了 AcidBubbles.Glance.23 这一个包

**Comment by zx20085121996** [comment]
感谢答复
