### ISSUE TITLE
在vambox内启动vr无法绕开steamvr，占用内存

### ISSUE THREAD

**Issue by GengAhChang** [NaturalWhiteX/vambox-release#9]
如果直接用VirtualDesktop在VAM文件夹内选择VaM(OpenVR).bat ，那么就会直接启动而不是先打开steamvr再从steamvr里启动，这样导致虽然vambox减少了启动文件但steamvr增加了显存占用，相比之下只好搁置vambox

**Comment by Hamakaze1s** [comment]
不从vambox启动游戏本体，vambox的功能也能正常生效
